server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location = /pokemonparty {
    return 308 /pokemonparty/;
  }

  location = /pokemonparty/music {
    try_files /pokemonparty/music.html =404;
  }

  location /pokemonparty/ {
    try_files $uri $uri/ /pokemonparty/index.html;
  }

  location / {
    return 404;
  }
}
